export const MONTHS = [
  { month: "January", abv: "Jan" },
  { month: "February", abv: "Feb" },
  { month: "March", abv: "Mar" },
  { month: "April", abv: "Apr" },
  { month: "May", abv: "May" },
  { month: "June", abv: "Jun" },
  { month: "July", abv: "Jul" },
  { month: "August", abv: "Aug" },
  { month: "September", abv: "Sep" },
  { month: "October", abv: "Oct" },
  { month: "November", abv: "Nov" },
  { month: "December", abv: "Dec" },
];

export const WEEKDAYS = [
  { day: "Sunday", abv: "Sun" },
  { day: "Monday", abv: "Mon" },
  { day: "Tuesday", abv: "Tue" },
  { day: "Wednesday", abv: "Wed" },
  { day: "Thursday", abv: "Thu" },
  { day: "Friday", abv: "Fri" },
  { day: "Saturday", abv: "Sat" },
];

interface State {
  value: string;
  text: string;
}

export const STATES: Array<State> = [
  { value: "al", text: "AL" },
  { value: "ak", text: "AK" },
  { value: "az", text: "AZ" },
  { value: "ar", text: "AR" },
  { value: "ca", text: "CA" },
  { value: "co", text: "CO" },
  { value: "ct", text: "CT" },
  { value: "de", text: "DE" },
  { value: "fl", text: "FL" },
  { value: "ga", text: "GA" },
  { value: "hi", text: "HI" },
  { value: "id", text: "ID" },
  { value: "il", text: "IL" },
  { value: "in", text: "IN" },
  { value: "ia", text: "IA" },
  { value: "ks", text: "KS" },
  { value: "ky", text: "KY" },
  { value: "la", text: "LA" },
  { value: "me", text: "ME" },
  { value: "md", text: "MD" },
  { value: "ma", text: "MA" },
  { value: "mi", text: "MI" },
  { value: "mn", text: "MN" },
  { value: "ms", text: "MS" },
  { value: "mo", text: "MO" },
  { value: "mt", text: "MT" },
  { value: "ne", text: "NE" },
  { value: "nv", text: "NV" },
  { value: "nh", text: "NH" },
  { value: "nj", text: "NJ" },
  { value: "nm", text: "NM" },
  { value: "ny", text: "NY" },
  { value: "nc", text: "NC" },
  { value: "nd", text: "ND" },
  { value: "oh", text: "OH" },
  { value: "ok", text: "OK" },
  { value: "or", text: "OR" },
  { value: "pa", text: "PA" },
  { value: "ri", text: "RI" },
  { value: "sc", text: "SC" },
  { value: "sd", text: "SD" },
  { value: "tn", text: "TN" },
  { value: "tx", text: "TX" },
  { value: "ut", text: "UT" },
  { value: "vt", text: "VT" },
  { value: "va", text: "VA" },
  { value: "wa", text: "WA" },
  { value: "wv", text: "WV" },
  { value: "wi", text: "WI" },
  { value: "wy", text: "WY" },
];
